run_name: flower_classification_run

# Data configuration
data:
  data_dir: data/raw
  image_size: 224
  batch_size: 16
  seed: 2024
  num_workers: 4
  split:
    train: 0.8
    val: 0.1
    test: 0.1

# Model configuration
model:
  model_name: rexnet_150
  num_classes: 5
  learning_rate: 0.001
  contrastive_margin: 0.3
  epochs: 25
  monitor_metric: val_loss
  monitor_mode: min
  patience: 10

# Paths
paths:
  save_dir: models
  plots_dir: plots
  data_dir: data/raw

# Trainer
trainer:
  accelerator: auto
  devices: auto
  max_epochs: 25
  log_every_n_steps: 10
  precision: '16-mixed'

# Callbacks
callbacks:
  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 1
    filename: best_model
    save_last: true
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 10
    verbose: true

# MLflow
mlflow:
  experiment_name: flower_classification
  tracking_uri: file:./mlruns
